spring:
  application:
    name: virtual-receptionist-api
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:virtual_receptionist
    username: root
    password: 12345
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
